language: java
jdk:
- openjdk10

before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

addons:
  sonarcloud:
    organization: artcomputerse
    token:
      secure: IrZTPm3ZDGKa09JvernpGqJB8VpInIL/1gdkFkE9JwELeRLOUKwahpkL+aA4k2LzeQATIwRrScDqgLXQBwkFGb2wxIc67wIiotOslvbEoJv0JmgJrhEbud2oap/isN+sGF7Npo4H05JtF8fX/FgwJqq48Re6p+Xf/NHjhZbGdX03smwtZCQ9UA5LInEpwrVE7B51MBlzIMpoPZYmzGTpddrFHkn9kNZNBcSa3UYAZAH2CbpLLflzvlZ1lSFfMUlJjxuX31Raszxr3N98wYo9gj80X8h3f+2fkFCijF0eKIetlJAkfeeRC5FWSpz9xdHgdmRbmC+YluUGCDfZngXJEpIo8ZZCQg57c2/Pu3u9IBekQRvuvJofeB0izOUE0HUqk6TviCQcab4qbGVkzjIysoDM7XeKzQ935NjqGRoCu6QVC/2BV5xSBu/od6DcN/NqcvwY+had2Sm1k3pZb+gX/UNmHMTtW9rdx8f5zdJO7kW55rDwDtrfsc6u2uVNEfdnkaRE/Meo5dmk/0l+P/nX09rJ/pUAWL/SFHkvaBrQV47yBB8qGUOqfL7AczZU8xv8ciU8Ul6Z5pdad2CYOIlVtI0UCaAwlIYufNdxN6qgyEogZL4k6iTMf6d9y3afDFsVDcOpYoQpHCA9zf1YXZejm8fnIiXzQDZkJQWZjqltCgU=

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

deploy:
- provider: bintray
  file: "bintray.json"
  user: "perty"
  key:
     secure: "mVEXwBebjLHUDCQwy4GRFu8sQpSisr2IBEXvy5zB0HggtpzejNFKUs0RA+GvvfMhgb3xLwbiSj4ePKXKyMIjPf1MrSD7z/YzcsB3z1OhfCyR8stwyq/xofmwTS1GJaeObUPKqxjlvJSqZivSJtek1fufqnjvmmEDh0M/ODfTIl5M4hRvyVX5yZbMTok6lHp8UEABuRTHpJzC62olTHNMgsRUp9fan697N0yA/N4aW4+Cx2xf0aylp66Gkl3p71cKRxVF+lcMUmdqWwFNhEe2P/g9nXAhx23kcYwC1TeDLKbckKaVPGsNtxENjtKzleOCOKDYh8A8C3WZEDVMUtwnm3K39rXAefbHcP/Lj3/okR65pzdyVOKucVxNTybqSJ2nWXoHwtvldf+HJ+1ACAtxHVxsU50XtV1o8bXsjuk8e7snqHihAIW3ww6W/CEYLhlit2PMBZ7GJnOmMEooHP4Usfb/sy9vop22LoCLzuZ3xMt+yvlAXSXW42W9tQxkcUwM0G3x//caVlHcmFgMYsyIZCHfDdVfk5mnjCwaK03yyVrK5Gsobb7bCDiWykvGlO11tsdggu3GwBAHK2OdQbMOGqLPhqkQ0lAXoXAd28/hM4JlQg7WpSKq/5yU1pIGN9L38s6LXCtJgCxntMpGTA+R5VvqmQFAEhCO7maCM63ntWc="
  skip_cleanup: true # to upload artifacts created during the build
  on:
    all_branches: true
- provider: releases
  api_key:
    secure: bWrkr/1er0iBnUd0feHkBPB2+mlVMqyk3bpHTTELWV8CreCzmkSFRdV9841F6BwVj7JOvZ4IFY1GdLcgEFpF2sf57yhUlonxMdQba1F75A0lRkVyD8wNKFYQShJIGbr5F01oAmcX0ED4L48S9EdAsgMvwhxPx5o0UI/pn/biCzi2cwVzA87flZvAlBLc2adolT5r6rJ1oO7CEJ3K+F4UXjDhDFBSH5gUandB6O4VGyOMjOveY0trGXNNY1n2KQ26M+QGfIerivVnzA1DKR4UsM+s1m1Nob7JRu/A00KhkDV6KC9LwjDrH4gR4e8SM+lmoxfFdvhokyi6UJo+Otxe/rF6hNdaGyt3u1LGPQraRZLEA+xNSggqhESBM965F2Vb8i9DV5U5mgdi2DkDosaPh7CfXcpsVc2yAmmCDDPMcrZW1YvbVwycS+4OkvaTeUV3nmLwE9ZquFku8Rj5/5lbmAHor8Vn0mwOTc3ODTi/k/LKD/l49Rtsjw8CZj9Z8t6O6uE64HUMJu6TDh0rum8CCgNG3xZRMm/RpfMa5AkqKwC9KuB3n6oOOGiFoMGQBGbJEoNw8Lkk1KCJwD0CWdFDCVWfXeVX5t+LjtlCW08x4VLHhJa50Gulrp5BpaSg4Uhd0EMCNikn7XqlPvXbUNhPruwz1isSOF6fZVp0G6Krpjk=
  file: ajavahtmlrenderer/target/ajavahtmlrenderer-$project_version.jar
  skip_cleanup: true
  on:
    repo: ArtComputerSE/ajavahtmlrenderer
    tags: true
  name: $project_version



